# Generated by Django 5.0.3 on 2024-05-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0003_alter_pokemon_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='subtype',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
