# Generated by Django 5.0.3 on 2024-05-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0004_alter_pokemon_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_of_birth', models.IntegerField()),
                ('sport_type', models.CharField(max_length=128)),
                ('nationality', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='subtype',
            field=models.CharField(max_length=128),
        ),
    ]
