# Generated by Django 5.0.3 on 2024-06-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0006_remove_athlete_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pokemon',
        ),
    ]
