# Generated by Django 5.0.3 on 2024-06-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0007_delete_pokemon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.IntegerField()),
                ('type', models.CharField(max_length=128)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
    ]
