# Generated by Django 5.0.3 on 2024-06-17 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0008_pokemon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pokemon',
        ),
    ]
