# Generated by Django 5.0.3 on 2024-06-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0009_delete_pokemon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Athlete',
        ),
    ]
